# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: UltimatumGamer
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: mastered
          plugin_topics_sort: stars
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 10
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current

